# Generated by Django 5.1.2 on 2025-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_financialgoal_budgetlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
    ]
